package mcc.survey.creator.model;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

@Entity
@Data
public class Survey {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String surveyMode; // e.g., "public", "access_code", "personal_access_code"

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User owner;

    @CreationTimestamp
    @Temporal(TemporalType.TIMESTAMP)
    private Date creationDate;

    @UpdateTimestamp
    @Temporal(TemporalType.TIMESTAMP)
    private Date modificationDate;

    private String dataClassification; // e.g., "public", "restricted", "confidential"

    private String status; // e.g., "drafted", "published", "expired", "deleted"

    @Lob
    private String surveyJson; // Store SurveyJS JSON definition

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "survey_shared_users",
            joinColumns = @JoinColumn(name = "survey_id"),
            inverseJoinColumns = @JoinColumn(name = "user_id")
    )
    private Set<User> sharedWithUsers = new HashSet<>();

    public Survey() {
    }

    public Survey(String surveyMode, User owner, String dataClassification, String status, String surveyJson) {
        this.surveyMode = surveyMode;
        this.owner = owner;
        this.dataClassification = dataClassification;
        this.status = status;
        this.surveyJson = surveyJson;
    }
    public User getOwner() {
        return owner;
    }
    public void setOwner(User owner) {
        this.owner = owner;
    }
    public String getSurveyMode() {
        return surveyMode;
    } 
    public void setSurveyMode(String surveyMode) {
        this.surveyMode = surveyMode;
    }
    public String getDataClassification() {
        return dataClassification;
    }
    public void setDataClassification(String dataClassification) {
        this.dataClassification = dataClassification;
    }
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }
    public String getSurveyJson() {
        return surveyJson;
    }
    public void setSurveyJson(String surveyJson) {
        this.surveyJson = surveyJson;
    }
    public Set<User> getSharedWithUsers() {
        return sharedWithUsers;
    }
    public void setSharedWithUsers(Set<User> sharedWithUsers) {
        this.sharedWithUsers = sharedWithUsers;
    }


    // Getters and setters are automatically generated by Lombok @Data
}
